import type { AchievementDefinition } from './types';

export const DAILY_GOAL = 10;

export const STREAK_MILESTONES = [7, 14, 21, 30] as const;

export const CATEGORY_LABELS: Record<string, string> = {
  streak: 'Серия',
  words: 'Слова',
  decks: 'Наборы',
  tests: 'Тесты',
  reviews: 'Повторения',
  milestones: 'Вехи',
  special: 'Особые',
};

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ── STREAK ──
  {
    id: 'streak_7',
    category: 'streak',
    icon: '\uD83D\uDD25',
    title: 'Неделя в огне',
    description: 'Учись 7 дней подряд',
    condition: (ctx) => ctx.currentStreak >= 7 || ctx.longestStreak >= 7,
    progressMax: 7,
    getProgress: (ctx) => Math.min(ctx.currentStreak, 7),
  },
  {
    id: 'streak_14',
    category: 'streak',
    icon: '\uD83D\uDD25\uD83D\uDD25',
    title: 'Две недели!',
    description: 'Учись 14 дней подряд',
    condition: (ctx) => ctx.currentStreak >= 14 || ctx.longestStreak >= 14,
    progressMax: 14,
    getProgress: (ctx) => Math.min(ctx.currentStreak, 14),
  },
  {
    id: 'streak_21',
    category: 'streak',
    icon: '\uD83D\uDC8E',
    title: 'Привычка!',
    description: 'Учись 21 день подряд',
    condition: (ctx) => ctx.currentStreak >= 21 || ctx.longestStreak >= 21,
    progressMax: 21,
    getProgress: (ctx) => Math.min(ctx.currentStreak, 21),
  },
  {
    id: 'streak_30',
    category: 'streak',
    icon: '\uD83D\uDC51',
    title: 'Месяц без перерыва',
    description: 'Учись 30 дней подряд',
    condition: (ctx) => ctx.currentStreak >= 30 || ctx.longestStreak >= 30,
    progressMax: 30,
    getProgress: (ctx) => Math.min(ctx.currentStreak, 30),
  },

  // ── WORDS ──
  {
    id: 'words_1',
    category: 'words',
    icon: '\uD83C\uDF31',
    title: 'Первое слово',
    description: 'Выучи первое слово',
    condition: (ctx) => ctx.totalMastered >= 1,
  },
  {
    id: 'words_10',
    category: 'words',
    icon: '\uD83C\uDF3F',
    title: 'Десяточка',
    description: 'Выучи 10 слов',
    condition: (ctx) => ctx.totalMastered >= 10,
    progressMax: 10,
    getProgress: (ctx) => Math.min(ctx.totalMastered, 10),
  },
  {
    id: 'words_50',
    category: 'words',
    icon: '\uD83C\uDF33',
    title: 'Полсотни',
    description: 'Выучи 50 слов',
    condition: (ctx) => ctx.totalMastered >= 50,
    progressMax: 50,
    getProgress: (ctx) => Math.min(ctx.totalMastered, 50),
  },
  {
    id: 'words_100',
    category: 'words',
    icon: '\uD83C\uDFD4\uFE0F',
    title: 'Сотня!',
    description: 'Выучи 100 слов',
    condition: (ctx) => ctx.totalMastered >= 100,
    progressMax: 100,
    getProgress: (ctx) => Math.min(ctx.totalMastered, 100),
  },
  {
    id: 'words_500',
    category: 'words',
    icon: '\uD83D\uDE80',
    title: 'Полиглот',
    description: 'Выучи 500 слов',
    condition: (ctx) => ctx.totalMastered >= 500,
    progressMax: 500,
    getProgress: (ctx) => Math.min(ctx.totalMastered, 500),
  },
  {
    id: 'words_1000',
    category: 'words',
    icon: '\uD83C\uDFC6',
    title: 'Тысяча!',
    description: 'Выучи 1000 слов',
    condition: (ctx) => ctx.totalMastered >= 1000,
    progressMax: 1000,
    getProgress: (ctx) => Math.min(ctx.totalMastered, 1000),
  },

  // ── DECKS ──
  {
    id: 'deck_1',
    category: 'decks',
    icon: '\uD83D\uDCD7',
    title: 'Первый набор',
    description: 'Полностью выучи один набор',
    condition: (ctx) => ctx.decksCompleted >= 1,
  },
  {
    id: 'deck_3',
    category: 'decks',
    icon: '\uD83D\uDCDA',
    title: 'Книголюб',
    description: 'Полностью выучи 3 набора',
    condition: (ctx) => ctx.decksCompleted >= 3,
    progressMax: 3,
    getProgress: (ctx) => Math.min(ctx.decksCompleted, 3),
  },
  {
    id: 'deck_10',
    category: 'decks',
    icon: '\uD83C\uDF93',
    title: 'Эрудит',
    description: 'Полностью выучи 10 наборов',
    condition: (ctx) => ctx.decksCompleted >= 10,
    progressMax: 10,
    getProgress: (ctx) => Math.min(ctx.decksCompleted, 10),
  },

  // ── TESTS ──
  {
    id: 'first_test',
    category: 'tests',
    icon: '\uD83C\uDFAF',
    title: 'Первый тест',
    description: 'Пройди первый тест',
    condition: (ctx) => ctx.totalTestsPassed >= 1,
  },
  {
    id: 'tests_50',
    category: 'tests',
    icon: '\uD83C\uDFAF',
    title: 'Полсотни тестов',
    description: 'Правильно ответь на 50 тестовых вопросов',
    condition: (ctx) => ctx.totalTestsPassed >= 50,
    progressMax: 50,
    getProgress: (ctx) => Math.min(ctx.totalTestsPassed, 50),
  },
  {
    id: 'tests_200',
    category: 'tests',
    icon: '\uD83C\uDFC5',
    title: 'Мастер тестов',
    description: 'Правильно ответь на 200 тестовых вопросов',
    condition: (ctx) => ctx.totalTestsPassed >= 200,
    progressMax: 200,
    getProgress: (ctx) => Math.min(ctx.totalTestsPassed, 200),
  },
  {
    id: 'perfect_test',
    category: 'tests',
    icon: '\uD83D\uDCAF',
    title: 'Без ошибок',
    description: 'Пройди тестовую сессию без единой ошибки',
    condition: (ctx) => ctx.perfectTestSessions >= 1,
  },
  {
    id: 'perfect_5',
    category: 'tests',
    icon: '\uD83C\uDF1F',
    title: 'Перфекционист',
    description: 'Пройди 5 безошибочных тестовых сессий',
    condition: (ctx) => ctx.perfectTestSessions >= 5,
    progressMax: 5,
    getProgress: (ctx) => Math.min(ctx.perfectTestSessions, 5),
  },

  // ── DICTATION ──
  {
    id: 'first_dictation',
    category: 'tests',
    icon: '\u270D\uFE0F',
    title: 'Первый диктант',
    description: 'Правильно напиши первое слово в диктанте',
    condition: (ctx) => ctx.totalDictationsPassed >= 1,
  },
  {
    id: 'dictation_50',
    category: 'tests',
    icon: '\u270D\uFE0F',
    title: 'Грамотей',
    description: 'Правильно напиши 50 слов в диктантах',
    condition: (ctx) => ctx.totalDictationsPassed >= 50,
    progressMax: 50,
    getProgress: (ctx) => Math.min(ctx.totalDictationsPassed, 50),
  },

  // ── AUDIO ──
  {
    id: 'first_audio',
    category: 'tests',
    icon: '\uD83C\uDFA7',
    title: 'Первый аудио-тест',
    description: 'Пройди первый аудио-тест',
    condition: (ctx) => ctx.totalAudioPassed >= 1,
  },
  {
    id: 'audio_50',
    category: 'tests',
    icon: '\uD83C\uDFB5',
    title: 'Острый слух',
    description: 'Правильно ответь на 50 аудио-вопросов',
    condition: (ctx) => ctx.totalAudioPassed >= 50,
    progressMax: 50,
    getProgress: (ctx) => Math.min(ctx.totalAudioPassed, 50),
  },

  // ── REVIEWS ──
  {
    id: 'first_review',
    category: 'reviews',
    icon: '\uD83D\uDD04',
    title: 'Первое повторение',
    description: 'Сделай первое повторение',
    condition: (ctx) => ctx.totalReviews >= 1,
  },
  {
    id: 'reviews_100',
    category: 'reviews',
    icon: '\uD83D\uDD04',
    title: '100 повторений',
    description: 'Сделай 100 повторений',
    condition: (ctx) => ctx.totalReviews >= 100,
    progressMax: 100,
    getProgress: (ctx) => Math.min(ctx.totalReviews, 100),
  },
  {
    id: 'reviews_500',
    category: 'reviews',
    icon: '\uD83E\uDDE0',
    title: 'Крепкая память',
    description: 'Сделай 500 повторений',
    condition: (ctx) => ctx.totalReviews >= 500,
    progressMax: 500,
    getProgress: (ctx) => Math.min(ctx.totalReviews, 500),
  },

  // ── MILESTONES ──
  {
    id: 'first_session',
    category: 'milestones',
    icon: '\uD83C\uDFAC',
    title: 'Начало пути',
    description: 'Начни первую учебную сессию',
    condition: (ctx) => ctx.totalStudySessions >= 1,
  },
  {
    id: 'sessions_50',
    category: 'milestones',
    icon: '\uD83D\uDCC6',
    title: '50 сессий',
    description: 'Проведи 50 учебных сессий',
    condition: (ctx) => ctx.totalStudySessions >= 50,
    progressMax: 50,
    getProgress: (ctx) => Math.min(ctx.totalStudySessions, 50),
  },
  {
    id: 'active_7',
    category: 'milestones',
    icon: '\uD83D\uDCC5',
    title: 'Неделя активности',
    description: 'Занимайся 7 разных дней',
    condition: (ctx) => ctx.daysActive >= 7,
    progressMax: 7,
    getProgress: (ctx) => Math.min(ctx.daysActive, 7),
  },
  {
    id: 'active_30',
    category: 'milestones',
    icon: '\uD83D\uDDD3\uFE0F',
    title: 'Месяц активности',
    description: 'Занимайся 30 разных дней',
    condition: (ctx) => ctx.daysActive >= 30,
    progressMax: 30,
    getProgress: (ctx) => Math.min(ctx.daysActive, 30),
  },

  // ── SPECIAL ──
  {
    id: 'night_owl',
    category: 'special',
    icon: '\uD83E\uDD89',
    title: 'Ночная сова',
    description: 'Позанимайся после 23:00',
    condition: (ctx) => ctx.currentHour >= 23,
  },
  {
    id: 'early_bird',
    category: 'special',
    icon: '\uD83D\uDC26',
    title: 'Ранняя пташка',
    description: 'Позанимайся до 7:00 утра',
    condition: (ctx) => ctx.currentHour < 7,
  },
];
